# Generated by Django 5.0.6 on 2024-06-02 05:17

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    # 创建用户组
    Group.objects.get_or_create(name='user')
    Group.objects.get_or_create(name='merchant')
    Group.objects.get_or_create(name='manager')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # 这是初始迁移文件，没有依赖项
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
