# Generated by Django 5.0.6 on 2024-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
